### ISSUE TITLE
Different predictions of the same model.dill file in different CPUs for the LinUCB algorithm

### ISSUE THREAD

**Issue by SaifJawaid** [david-cortes/contextualbandits#50]
After training the LinUCB model, I shared the model with another user. The other user was getting different scores for the arms for the same data. Any idea why?

**Comment by david-cortes** [comment]
If you are using it with the default arguments, there can be very small differences between runs even in the same CPU due to the linear algebra libraries used as backend for NumPy matrix operations (e.g. MKL, OpenBLAS). If that's a problem, you'll have to configure them to run single-threaded.

If you are using it with the arguments from the python notebook, there likely is some randomization in the choices (you can check the docs for `beta_prior` and `noise_to_smooth`), which itself depends on NumPy's generators which don't have any reproducibility guarantees across different setups.
