### ISSUE TITLE
Support for continuous rewards

### ISSUE THREAD

**Issue by Yalikesifulei** [david-cortes/contextualbandits#52]
It is said in the documentation that only binary rewards are supported. If continuous values are passed, the following sklearn exception is thrown:
```Python
ValueError: Unknown label type: 'continuous'
```
However, looks like there are no exceptions or errors when some regressor is used as `base_algorithm`, e.g.
```Python
agent = SeparateClassifiers(base_algorithm=RandomForestRegressor(), n_choices=...)
```
I haven't faced any unexpected behaviour for my use case. So, was it just luck or it is really a way to work with continuous rewards?

**Comment by david-cortes** [comment]
There aren't many explicit error checks in this library, but many things here assume that the rewards are binary - for example, by default, most classes in the online module will have a non-None value for `beta_prior`, which will cause it to output (0,1) values in some cases and maybe cause weird behavior if passed other values, and the same if you instead pass something for `smoothing`.

You _might_ be able to use `SeparateClassifiers` with a regressor and non-binary rewards if you disable `beta_prior` and use `batch_train=False`, but there's no guarantees that it will not error out due to some other functionality in there that assumes binary rewards.
